name: Trigger auto deployment for skp88

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/skp88-AutoDeployTrigger-59fc0a45-6c7b-4f6f-9ad2-6aa6c6a6af10.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: hub.docker.com
          username: ${{ secrets.SKP88_REGISTRY_USERNAME }}
          password: ${{ secrets.SKP88_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: hub.docker.com/devops:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SKP88_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n skp88 -g skp-docker --server hub.docker.com --username  ${{ secrets.SKP88_REGISTRY_USERNAME }} --password ${{ secrets.SKP88_REGISTRY_PASSWORD }}
            az containerapp update -n skp88 -g skp-docker --image hub.docker.com/devops:${{ github.sha }}
